plugins {
    id 'com.android.application'
}

android {
    namespace 'com.samosaking.admin'
    compileSdk 35
    defaultConfig {
        applicationId 'com.samosaking.admin'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.18.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'androidx.core:core:1.15.0'
}
