package com.samosaking.admin;

import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.webkit.*;import androidx.core.app.ActivityCompat;import com.google.firebase.FirebaseApp;import com.google.firebase.FirebaseOptions;import com.google.firebase.auth.*;import com.google.firebase.firestore.*;import org.json.*;import java.util.*;

public class AdminActivity extends Activity{
 private WebView w; private FirebaseAuth auth; private FirebaseFirestore db; private ListenerRegistration ordersListener; private boolean ready=false, firstSnapshot=true; private final Map<String,String> menuNames=new HashMap<>();
 private static final String PROJECT="samosa-king-3b90d", APP_ID="1:855148039257:android:535730f98ea24e77253548", API_KEY="AIzaSyCusjrBM2M59Obiwv-Dgy1m6PgiYDQtwQw";
 @Override public void onCreate(Bundle b){super.onCreate(b); if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel("admin_orders","New Orders",NotificationManager.IMPORTANCE_HIGH)); FirebaseOptions o=new FirebaseOptions.Builder().setApiKey(API_KEY).setProjectId(PROJECT).setApplicationId(APP_ID).build(); try{FirebaseApp.initializeApp(this,o);}catch(Exception ignored){} auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance();w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);w.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){if(!ready){ready=true;showLogin();}} public boolean shouldOverrideUrlLoading(WebView v,String u){try{if(u.startsWith("tel:")||u.startsWith("https://wa.me/")){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));return true;}}catch(Exception ignored){}return false;}});w.addJavascriptInterface(new Bridge(),"AdminNative");setContentView(w);w.loadUrl("file:///android_asset/admin.html");}
 private void js(String x){runOnUiThread(()->{if(w!=null)w.evaluateJavascript(x,null);});}
 private void showLogin(){js("window.showLogin()");}
 private void login(String email,String pass){if(email==null||pass==null||email.trim().isEmpty()||pass.isEmpty()){js("window.loginError('Email and password are required.')");return;}auth.signInWithEmailAndPassword(email.trim(),pass).addOnSuccessListener(r->checkAdmin()).addOnFailureListener(e->js("window.loginError("+JSONObject.quote("Login failed: "+e.getMessage())+")"));}
 private void checkAdmin(){FirebaseUser u=auth.getCurrentUser();if(u==null){showLogin();return;}db.collection("admins").document(u.getUid()).get().addOnSuccessListener(d->{if(!d.exists()){auth.signOut();js("window.loginError('This account is not an authorized Samosa King admin.')");return;}js("window.showDashboard("+JSONObject.quote(u.getEmail()==null?"Admin":u.getEmail())+")");loadMenu();listenOrders();}).addOnFailureListener(e->{auth.signOut();js("window.loginError('Admin verification failed. Check Firebase rules.')");});}
 private void loadMenu(){db.collection("menu").get().addOnSuccessListener(s->{menuNames.clear();for(DocumentSnapshot d:s){String id=d.getId();String n=d.getString("name");if(n!=null)menuNames.put(id,n);}loadOrdersOnce();});}
 private void loadOrdersOnce(){if(auth.getCurrentUser()==null)return;db.collection("orders").get().addOnSuccessListener(s->sendOrders(s.getDocuments()));}
 private void listenOrders(){if(ordersListener!=null)ordersListener.remove();ordersListener=db.collection("orders").addSnapshotListener((s,e)->{if(e!=null||s==null)return;sendOrders(s.getDocuments());if(!firstSnapshot){int placed=0;for(DocumentSnapshot d:s.getDocuments())if("PLACED".equals(d.getString("status")))placed++;if(placed>0)notifyNewOrder(placed);}firstSnapshot=false;});}
 private void notifyNewOrder(int count){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);Notification n=new Notification.Builder(this,"admin_orders").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("Samosa King – New Order").setContentText(count==1?"New order received":"New orders received").setAutoCancel(true).build();nm.notify((int)(System.currentTimeMillis()%100000),n);}
 private void sendOrders(List<DocumentSnapshot> docs){try{JSONArray a=new JSONArray();for(DocumentSnapshot d:docs){JSONObject o=new JSONObject();o.put("id",d.getId());o.put("name",String.valueOf(d.get("customerName")));o.put("mobile",String.valueOf(d.get("mobile")));o.put("address",String.valueOf(d.get("address")));o.put("payment",String.valueOf(d.get("paymentMethod")));o.put("subtotal",d.getLong("subtotal")!=null?d.getLong("subtotal"):0);o.put("delivery",d.getLong("deliveryFee")!=null?d.getLong("deliveryFee"):0);o.put("discount",d.getLong("discount")!=null?d.getLong("discount"):0);o.put("total",d.getLong("total")!=null?d.getLong("total"):0);o.put("status",String.valueOf(d.get("status")));Date dt=d.getDate("createdAt");o.put("date",dt==null?"Just now":dt.toString());Map<String,Object> im=d.get("items",Map.class);JSONArray items=new JSONArray();if(im!=null)for(Map.Entry<String,Object> x:im.entrySet()){JSONObject z=new JSONObject();z.put("id",x.getKey());z.put("name",menuNames.containsKey(x.getKey())?menuNames.get(x.getKey()):x.getKey());z.put("qty",((Number)x.getValue()).intValue());items.put(z);}o.put("items",items);a.put(o);}js("window.ordersResult("+JSONObject.quote(a.toString())+")");}catch(Exception e){js("window.adminError('Could not read orders.')");}}
 private void updateStatus(String id,String status){FirebaseUser u=auth.getCurrentUser();if(u==null)return;db.collection("admins").document(u.getUid()).get().addOnSuccessListener(d->{if(!d.exists()){js("window.adminError('Admin access denied.')");return;}db.collection("orders").document(id).update("status",status).addOnSuccessListener(x->js("window.actionDone('Order updated to "+status.replace("_"," ")+"')")).addOnFailureListener(e->js("window.adminError("+JSONObject.quote("Update failed: "+e.getMessage())+")"));});}
 private void reject(String id){updateStatus(id,"REJECTED");}
 private void logout(){if(ordersListener!=null)ordersListener.remove();firstSnapshot=true;auth.signOut();js("window.showLogin()");}
 private void nav(String address){try{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/dir/?api=1&destination="+Uri.encode(address)+"&travelmode=driving"));startActivity(i);}catch(Exception ignored){}}
 private void call(String number){try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+number)));}catch(Exception ignored){}}
 private void whatsapp(String number){try{String n=number.replaceAll("[^0-9]","");if(n.length()==10)n="91"+n;startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+n)));}catch(Exception ignored){}}
 public class Bridge{@JavascriptInterface public void login(String e,String p){runOnUiThread(()->login(e,p));}@JavascriptInterface public void refresh(){runOnUiThread(()->{loadMenu();loadOrdersOnce();});}@JavascriptInterface public void updateStatus(String id,String st){runOnUiThread(()->updateStatus(id,st));}@JavascriptInterface public void reject(String id){runOnUiThread(()->reject(id));}@JavascriptInterface public void logout(){runOnUiThread(()->logout());}@JavascriptInterface public void navigate(String ad){runOnUiThread(()->nav(ad));}@JavascriptInterface public void call(String n){runOnUiThread(()->call(n));}@JavascriptInterface public void whatsapp(String n){runOnUiThread(()->whatsapp(n));}}
 @Override protected void onDestroy(){if(ordersListener!=null)ordersListener.remove();super.onDestroy();}
}
