package com.samosaking.admin;

import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.webkit.*;import android.graphics.Color;import android.widget.TextView;import org.json.*;

public class AdminActivity extends Activity{
 private WebView w;
 @Override public void onCreate(Bundle b){super.onCreate(b);try{w=new WebView(this);w.setBackgroundColor(Color.WHITE);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);w.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){v.evaluateJavascript("window.showDashboard('Admin')",null);} @Override public boolean shouldOverrideUrlLoading(WebView v,String u){try{if(u.startsWith("tel:")||u.startsWith("https://wa.me/")){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));return true;}}catch(Exception ignored){}return false;}});w.addJavascriptInterface(new Bridge(),"AdminNative");setContentView(w);w.loadUrl("file:///android_asset/admin.html");}catch(Throwable e){TextView t=new TextView(this);t.setText("Samosa King ADMIN\n\nAdmin screen startup error: "+e.getClass().getSimpleName());t.setTextSize(18);t.setTextColor(Color.DKGRAY);t.setPadding(40,80,40,40);setContentView(t);}}
 private void message(String x){runOnUiThread(()->{if(w!=null)w.evaluateJavascript("window.adminError("+JSONObject.quote(x)+")",null);});}
 private void call(String n){try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+n)));}catch(Exception e){message("Could not open phone dialer.");}}
 private void whatsapp(String n){try{String x=n.replaceAll("[^0-9]","");if(x.length()==10)x="91"+x;startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+x)));}catch(Exception e){message("Could not open WhatsApp.");}}
 private void nav(String a){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/dir/?api=1&destination="+Uri.encode(a)+"&travelmode=driving")));}catch(Exception e){message("Could not open Maps.");}}
 public class Bridge{@JavascriptInterface public void login(String e,String p){message("Login is temporarily disabled. Direct Admin mode is open.");}@JavascriptInterface public void refresh(){message("Direct Admin mode: Firebase login will be added later.");}@JavascriptInterface public void updateStatus(String id,String st){message("Status update will be enabled after Admin login is added.");}@JavascriptInterface public void reject(String id){message("Reject will be enabled after Admin login is added.");}@JavascriptInterface public void logout(){w.evaluateJavascript("window.showDashboard('Admin')",null);}@JavascriptInterface public void navigate(String ad){runOnUiThread(()->nav(ad));}@JavascriptInterface public void call(String n){runOnUiThread(()->call(n));}@JavascriptInterface public void whatsapp(String n){runOnUiThread(()->whatsapp(n));}}
 @Override public void onBackPressed(){if(w!=null&&w.canGoBack())w.goBack();else super.onBackPressed();}
 @Override protected void onDestroy(){super.onDestroy();}
}
