package com.samosaking.nawalgarh;
import android.content.Intent;import android.net.Uri;import android.webkit.JavascriptInterface;import android.webkit.WebView;import com.google.firebase.auth.FirebaseAuth;import com.google.firebase.firestore.*;import org.json.*;import java.util.*;
public class AdminBridge{
 private final MainActivity a;private final WebView w;private final FirebaseFirestore db;private final FirebaseAuth auth;
 AdminBridge(MainActivity a,WebView w){this.a=a;this.w=w;db=FirebaseFirestore.getInstance();auth=FirebaseAuth.getInstance();}
 private void js(String s){a.runOnUiThread(()->w.evaluateJavascript(s,null));}private boolean signed(){return auth.getCurrentUser()!=null;}private boolean isAdminUid(){return signed() && "vJCq3yQDe0QcCg5EoEPnjVKwUgJ2".equals(auth.getCurrentUser().getUid());}private void admin(Runnable r){if(!signed()){js("window.adminError('Login required.')");return;}if(!isAdminUid()){js("window.adminError('Admin access denied.')");return;}r.run();}
 @JavascriptInterface public void openShopNavigation(){a.runOnUiThread(()->{try{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("google.navigation:q=27.8514056,75.2711528&mode=d"));i.setPackage("com.google.android.apps.maps");try{a.startActivity(i);return;}catch(Exception ignored){}Intent g=new Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q=27.8514056,75.2711528(Samosa%20King%20Nawalgarh)"));try{a.startActivity(g);return;}catch(Exception ignored){}a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/dir/?api=1&destination=27.8514056,75.2711528&travelmode=driving")));}catch(Exception ignored){}});}
 @JavascriptInterface public void validateCoupon(String code,int subtotal){String k=code==null?"":code.trim().toUpperCase(Locale.US);if(k.isEmpty()){js("window.couponResult(false,0,'Enter coupon code.')");return;}db.collection("coupons").document(k).get().addOnSuccessListener(d->{if(!d.exists()||!Boolean.TRUE.equals(d.getBoolean("enabled"))){js("window.couponResult(false,0,'Invalid or inactive coupon.')");return;}Long min=d.getLong("minOrder"),val=d.getLong("value");if(min!=null&&subtotal<min){js("window.couponResult(false,0,'Minimum order is ₹"+min+".')");return;}if(Boolean.TRUE.equals(d.getBoolean("firstOnly"))){js("window.couponResult(false,0,'This first-order coupon requires secure server-side first-order validation.')");return;}long v=val==null?0:val;long disc="PERCENT".equals(d.getString("type"))?Math.min(subtotal,(subtotal*v)/100):Math.min(subtotal,v);js("window.couponResult(true,"+disc+",'Coupon applied.')");}).addOnFailureListener(e->js("window.couponResult(false,0,'Coupon validation failed.')"));}
 @JavascriptInterface public void loadDashboard(){admin(()->db.collection("orders").get().addOnSuccessListener(s->{long sales=0,today=0;int placed=0,del=0;Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);Date start=c.getTime();for(DocumentSnapshot d:s){Long t=d.getLong("total");String st=d.getString("status");Date dt=d.getDate("createdAt");if(t!=null&&"DELIVERED".equals(st)){sales+=t;del++;if(dt!=null&&dt.after(start))today+=t;}if("PLACED".equals(st))placed++;}js("window.adminDashboard("+sales+","+today+","+placed+","+del+","+s.size()+")");}));}
 @JavascriptInterface public void loadReviews(){admin(()->db.collection("reviews").get().addOnSuccessListener(s->{try{JSONArray out=new JSONArray();for(DocumentSnapshot d:s){JSONObject o=new JSONObject();o.put("id",d.getId());o.put("orderId",String.valueOf(d.get("orderId")));o.put("rating",d.getLong("rating")!=null?d.getLong("rating"):0);o.put("comment",String.valueOf(d.get("comment")));o.put("date",d.getDate("createdAt")!=null?d.getDate("createdAt").toString():"Recent");out.put(o);}js("window.adminReviewsResult("+JSONObject.quote(out.toString())+")");}catch(Exception e){js("window.adminError('Could not load reviews.')");}}));}
 @JavascriptInterface public void loadMenu(){admin(()->db.collection("menu").get().addOnSuccessListener(s->{try{JSONArray out=new JSONArray();for(DocumentSnapshot d:s){JSONObject o=new JSONObject();o.put("id",d.getId());o.put("name",String.valueOf(d.get("name")));o.put("price",d.getLong("price")!=null?d.getLong("price"):0);o.put("enabled",!Boolean.FALSE.equals(d.getBoolean("enabled")));out.put(o);}js("window.adminMenuResult("+JSONObject.quote(out.toString())+")");}catch(Exception e){js("window.adminError('Could not load menu.')");}}));}
 @JavascriptInterface public void saveMenu(String id,String name,int price,boolean enabled){admin(()->{Map<String,Object>m=new HashMap<>();m.put("name",name);m.put("price",price);m.put("enabled",enabled);m.put("updatedAt",FieldValue.serverTimestamp());db.collection("menu").document(id).set(m,SetOptions.merge()).addOnSuccessListener(x->js("window.adminSaved('Menu updated.')"));});}
 @JavascriptInterface public void saveOffer(String id,String title,String type,int value,String code,boolean enabled){admin(()->{Map<String,Object>m=new HashMap<>();m.put("title",title);m.put("type",type);m.put("value",value);m.put("code",code.toUpperCase(Locale.US));m.put("enabled",enabled);m.put("updatedAt",FieldValue.serverTimestamp());db.collection("offers").document(id).set(m,SetOptions.merge()).addOnSuccessListener(x->js("window.adminSaved('Offer saved.')"));});}
 @JavascriptInterface public void saveCoupon(String code,String type,int value,int minOrder,boolean firstOnly,boolean enabled){admin(()->{String k=code.trim().toUpperCase(Locale.US);Map<String,Object>m=new HashMap<>();m.put("code",k);m.put("type",type);m.put("value",value);m.put("minOrder",minOrder);m.put("firstOnly",firstOnly);m.put("enabled",enabled);m.put("updatedAt",FieldValue.serverTimestamp());db.collection("coupons").document(k).set(m,SetOptions.merge()).addOnSuccessListener(x->js("window.adminSaved('Coupon saved.')"));});}
 @JavascriptInterface public void rejectOrder(String id){admin(()->db.collection("orders").document(id).update("status","REJECTED").addOnSuccessListener(x->js("window.adminSaved(\'Order rejected.\')")));}\n @JavascriptInterface public void deleteOrder(String id){admin(()->db.collection("orders").document(id).delete().addOnSuccessListener(x->js("window.adminSaved(\'Order deleted.\')")).addOnFailureListener(e->js("window.adminError(\'Could not delete order.\')")));}
 @JavascriptInterface public void loadStoreData(){db.collection("menu").get().addOnSuccessListener(menu->{try{JSONArray m=new JSONArray();for(DocumentSnapshot d:menu){JSONObject o=new JSONObject();o.put("id",d.getId());o.put("name",String.valueOf(d.get("name")));o.put("price",d.getLong("price")!=null?d.getLong("price"):0);o.put("enabled",!Boolean.FALSE.equals(d.getBoolean("enabled")));m.put(o);}db.collection("offers").get().addOnSuccessListener(offers->{try{JSONArray f=new JSONArray();for(DocumentSnapshot d:offers)if(!Boolean.FALSE.equals(d.getBoolean("enabled"))){JSONObject o=new JSONObject();o.put("id",d.getId());o.put("title",String.valueOf(d.get("title")));o.put("type",String.valueOf(d.get("type")));o.put("value",d.getLong("value")!=null?d.getLong("value"):0);o.put("code",String.valueOf(d.get("code")));f.put(o);}JSONObject all=new JSONObject();all.put("menu",m);all.put("offers",f);js("window.storeDataResult("+JSONObject.quote(all.toString())+")");}catch(Exception e){js("window.storeDataResult('{}')");}});}catch(Exception e){js("window.storeDataResult('{}')");}});
 }
}